version: '3'

services:
  reactapp:
    container_name: reactapp
    build: ./Frontend/sigomf
    image: reactapp:1.0
    ports:
      - 8084:80
    volumes:
      - ./Frontend/sigomf:/app
    environment:
      - NODE_ENV=development

  users:
    container_name: users
    build: Microservices/sigoms-users
    image: users:1.0
    ports:
      - 444:443
      - 8081:80
      - 9001:9000
    volumes:
      - ./Microservices/Users:/app