FROM rabbitmq:3.8.9-management

# ----------------------------------------------
# ----------[Configuração do ambiente]----------
# ----------------------------------------------

ADD config/definitions.json /opt/definitions.json
ADD config/rabbitmq.config /etc/rabbitmq/rabbitmq.config